# Generated by Django 4.2.1 on 2023-12-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjob',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='repeatablejob',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='scheduledjob',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='taskrunlog',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
