# Generated by Django 4.2.1 on 2023-09-20 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0002_datasource_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcetype',
            name='is_external_datasource',
            field=models.BooleanField(default=False, help_text='Is this an external data source?'),
        ),
    ]
