FROM ${REGISTRY:-}llmstack-api:${TAG:-latest} as builder
FROM nginx:stable-alpine3.17-slim

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

# Copy static files from Django to nginx
COPY --from=builder /code/static /usr/share/nginx/html/static