version: "3.8"

services:
  redis:
    image: redis:alpine
    ports:
      - "26379:6379"
    command: redis-server
    restart: unless-stopped
    volumes:
      - ${REDIS_VOLUME:-/tmp/redis_llmstack}:/data
  postgres:
    image: postgres:15.1-alpine
    ports:
      - "25432:5432"
    command: "postgres -c fsync=off -c full_page_writes=off -c synchronous_commit=OFF"
    restart: unless-stopped
    volumes:
      - ${POSTGRES_VOLUME:-/tmp/postgres_llmstack}:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      PGDATA: /var/lib/postgresql/data/pgdata
  api:
    build:
      context: .
      cache_from:
        - llmstack-api:latest
    command: apiserver
    volumes:
      - .:/code
    links:
      - postgres:postgres
    ports:
      - 9000:9000
    expose:
      - 9000
    env_file:
      - .env.dev
    cap_add:
      - SYS_PTRACE
  rqworker:
    build:
      context: .
      cache_from:
        - llmstack-rqworker:latest
    command: rqworker
    volumes:
      - .:/code
    depends_on:
      - redis
      - postgres
    links:
      - redis:redis
      - postgres:postgres
    env_file:
      - .env.dev
  weaviate:
    image: semitechnologies/weaviate:1.20.5
    ports:
      - 28080:8080
    volumes:
      - ${WEAVIATE_VOLUME:-/var/weaviate}:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: text2vec-openai
      ENABLE_MODULES: text2vec-openai
      CLUSTER_HOSTNAME: "weaviate-node"
