# Generated by Django 4.2.1 on 2023-09-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_defaultprofile_localai_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultprofile',
            name='anthropic_api_key',
            field=models.CharField(blank=True, default=None, help_text='Anthropic API key to use with Anthropic models like Claude', max_length=256, null=True),
        ),
    ]
