# Generated by Django 5.0 on 2024-04-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_defaultprofile__connections'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultprofile',
            name='mistral_api_key',
            field=models.CharField(blank=True, default=None, help_text='Mistral API key to use with Mistral backend', max_length=256, null=True),
        ),
    ]
