# Generated by Django 5.0.6 on 2024-06-04 07:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_defaultprofile_mistral_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='User UUID', unique=True),
        ),
    ]
