# Generated by Django 4.2.1 on 2023-10-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_migrate_access_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='twilio_integration_config',
            field=models.JSONField(blank=True, default=dict, help_text='Twilio config for this app'),
        ),
    ]
