# Generated by Django 4.2.10 on 2024-03-08 02:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_app_twilio_integration_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='store_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, help_text='Identifier for the app in the store', null=True),
        ),
    ]
