# Generated by Django 4.2.10 on 2024-03-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_app_store_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='store_uuid',
            field=models.UUIDField(blank=True, help_text='Identifier for the app in the store', null=True),
        ),
    ]
