# Generated by Django 4.2.11 on 2024-04-04 05:01

import django.contrib.postgres.fields
from django.db import migrations, models
import llmstack.apps.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_appdataassets'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSessionShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='UUID for the model')),
                ('code', models.CharField(help_text='Share code', max_length=7, unique=True)),
                ('app_session_uuid', models.UUIDField(blank=True, help_text='UUID of the app session', null=True)),
                ('run_entry_request_uuids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=None, help_text='List of run entry request UUIDs associated with the share', null=True, size=None)),
                ('visibility', models.PositiveSmallIntegerField(choices=[(0, 'Private'), (1, 'Organization'), (2, 'Unlisted'), (3, 'Public')], default=3, help_text='Visibility of the share')),
                ('metadata', models.JSONField(default=dict, help_text='Metadata for the share')),
            ],
        ),
        migrations.AlterField(
            model_name='appdataassets',
            name='file',
            field=models.FileField(blank=True, null=True, storage=llmstack.apps.models.select_storage, upload_to=llmstack.apps.models.appstore_upload_to),
        ),
    ]
