# Generated by Django 5.0.6 on 2024-09-26 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_alter_appdataassets_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='access_permission',
        ),
        migrations.RemoveField(
            model_name='app',
            name='accessible_by',
        ),
        migrations.RemoveField(
            model_name='app',
            name='config',
        ),
        migrations.RemoveField(
            model_name='app',
            name='data_transformer',
        ),
        migrations.RemoveField(
            model_name='app',
            name='input_schema',
        ),
        migrations.RemoveField(
            model_name='app',
            name='input_ui_schema',
        ),
        migrations.RemoveField(
            model_name='app',
            name='is_cloneable',
        ),
        migrations.RemoveField(
            model_name='app',
            name='output_template',
        ),
        migrations.RemoveField(
            model_name='app',
            name='run_graph',
        ),
        migrations.RemoveField(
            model_name='app',
            name='template',
        ),
    ]
