# Generated by Django 5.0.6 on 2024-11-01 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_remove_app_access_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='type_slug',
            field=models.CharField(blank=True, default='', help_text='Slug of the app type', max_length=100),
        ),
        migrations.AlterField(
            model_name='app',
            name='type',
            field=models.ForeignKey(blank=True, help_text='Type of the app', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apps.apptype'),
        ),
    ]
