# Generated by Django 4.2.14 on 2024-08-13 17:02

import uuid

from django.db import migrations, models

import llmstack.sheets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PromptlySheetFiles",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, help_text="UUID of the asset", unique=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict, help_text="Metadata for the asset", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ref_id", models.UUIDField(blank=True, help_text="UUID of the sheet this file belongs to")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=llmstack.sheets.models.PromptlySheetFiles.select_storage,
                        upload_to=llmstack.sheets.models.PromptlySheetFiles.sheet_upload_to,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PromptlySheet",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("profile_uuid", models.UUIDField(help_text="The UUID of the owner of the sheet")),
                ("name", models.CharField(help_text="The name of the sheet", max_length=255)),
                ("extra_data", models.JSONField(blank=True, help_text="Extra data for the sheet", null=True)),
                ("data", models.JSONField(blank=True, help_text="The data of the sheet", null=True)),
                ("is_locked", models.BooleanField(default=False, help_text="Whether the sheet is locked")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="The date and time the sheet was created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="The date and time the sheet was last updated"),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["profile_uuid"], name="promptly_sh_profile_38dc1d_idx")],
            },
        ),
    ]
