# Generated by Django 5.0.6 on 2024-09-26 18:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0006_add_pipeline_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='read_accessible_by',
            field=models.ManyToManyField(help_text='Users who can read the data source', related_name='read_accessible_datasources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datasource',
            name='write_accessible_by',
            field=models.ManyToManyField(help_text='Users who can write the data source', related_name='write_accessible_datasources', to=settings.AUTH_USER_MODEL),
        ),
    ]
