# Generated by Django 5.0.6 on 2024-09-26 21:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0007_datasource_read_accessible_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='read_accessible_by',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='write_accessible_by',
        ),
        migrations.AddField(
            model_name='datasource',
            name='read_accessible_by',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=320), blank=True, default=list, help_text='List of user emails or domains who can access the app', size=None),
        ),
        migrations.AddField(
            model_name='datasource',
            name='write_accessible_by',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=320), blank=True, default=list, help_text='List of user emails or domains who can modify the app', size=None),
        ),
    ]
