# Generated by Django 4.2.1 on 2023-09-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='config',
            field=models.JSONField(
                default=dict,
                help_text='Config for the data source'),
        ),
        migrations.AddField(
            model_name='datasourcetype',
            name='is_external_datasource',
            field=models.BooleanField(
                default=False,
                help_text='Is this an external data source?'),
        ),
    ]
