# Generated by Django 4.2.10 on 2024-03-17 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datasources', '0003_userfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfiles',
            name='user',
            field=models.ForeignKey(help_text='User this asset belongs to', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
