# Generated by Django 4.2.11 on 2024-07-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0004_alter_datasource_uuid_alter_datasourceentry_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='type_slug',
            field=models.CharField(default='', help_text='Slug of the data source type', max_length=50),
        ),
    ]
