# Generated by Django 4.2.11 on 2024-07-09 18:24

from django.db import migrations


def populate_type_slug(apps, schema_editor):
    DataSource = apps.get_model("datasources", "DataSource")
    for datasource in DataSource.objects.all():
        datasource.type_slug = datasource.type.slug
        datasource.save()


class Migration(migrations.Migration):

    dependencies = [
        ("datasources", "0005_datasource_type_slug"),
    ]

    operations = [migrations.RunPython(populate_type_slug)]
