# Generated by Django 4.2.1 on 2023-08-08 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apiabstractor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='app_session',
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text='App session this request was made for',
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='apps.appsession'),
        ),
        migrations.AddField(
            model_name='request',
            name='endpoint',
            field=models.ForeignKey(
                help_text='Version of endpoint this request made for',
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='apiabstractor.endpoint'),
        ),
        migrations.AddField(
            model_name='prompthub',
            name='share',
            field=models.ForeignKey(
                help_text='User prompt shared by user',
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='apiabstractor.share'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='request',
            field=models.ForeignKey(
                help_text='Request object this feedback is collected against',
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='apiabstractor.request'),
        ),
        migrations.AddField(
            model_name='endpointinvocationcount',
            name='user',
            field=models.ForeignKey(
                help_text='User this count is for',
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='api_backend',
            field=models.ForeignKey(
                help_text='Backend endpoint this eventually calls',
                on_delete=django.db.models.deletion.PROTECT,
                to='apiabstractor.apibackend'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='owner',
            field=models.ForeignKey(
                help_text='Owner of this endpoint',
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apibackend',
            name='api_provider',
            field=models.ForeignKey(
                help_text='API Group this endpoint belongs to',
                on_delete=django.db.models.deletion.PROTECT,
                to='apiabstractor.apiprovider'),
        ),
        migrations.AlterUniqueTogether(
            name='apibackend',
            unique_together={
                (
                    'api_provider',
                    'name')},
        ),
    ]
