# Generated by Django 4.2.11 on 2024-03-25 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apiabstractor', '0004_runentry_app_store_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runentry',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of the app or endpoint', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
