# Generated by Django 4.2.14 on 2024-08-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiabstractor', '0007_runentry_apiabstract_request_fb04e3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runentry',
            name='processor_runs_objref',
            field=models.CharField(blank=True, default=None, help_text='Processor runs objref', null=True),
        ),
        migrations.DeleteModel(
            name='EndpointInvocationCount',
        ),
    ]
