# Generated by Django 4.2.14 on 2024-08-09 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiabstractor', '0009_remove_runentry_processor_runs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='request',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='request',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='request',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='response',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
