# Generated by Django 4.2.14 on 2024-08-15 20:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apiabstractor', '0010_remove_response_request_remove_feedback_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='expected_response',
        ),
        migrations.AddField(
            model_name='feedback',
            name='request_uuid',
            field=models.CharField(default=uuid.uuid4, help_text='Reference to run entry', max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='response_feedback',
            field=models.TextField(help_text='Expected response for the response', null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='response_quality',
            field=models.SmallIntegerField(help_text='Quality rating for the response', max_length=10),
        ),
    ]
