# Generated by Django 5.0.6 on 2024-09-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiabstractor', '0012_runentry_usage_metrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='response_quality',
            field=models.SmallIntegerField(help_text='Quality rating for the response'),
        ),
    ]
