# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: runner.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0crunner.proto\"?\n\x0c\x42rowserInput\x12!\n\x04type\x18\x01 \x01(\x0e\x32\x13.BrowserCommandType\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"}\n\x0f\x42rowserInitData\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x1d\n\x15terminate_url_pattern\x18\x02 \x01(\t\x12\x0f\n\x07timeout\x18\x03 \x01(\x05\x12\x17\n\x0fpersist_session\x18\x04 \x01(\x08\x12\x14\n\x0csession_data\x18\x05 \x01(\t\"Y\n\x14RemoteBrowserRequest\x12#\n\tinit_data\x18\x01 \x01(\x0b\x32\x10.BrowserInitData\x12\x1c\n\x05input\x18\x05 \x01(\x0b\x32\r.BrowserInput\"<\n\x14RemoteBrowserSession\x12\x0e\n\x06ws_url\x18\x01 \x01(\t\x12\x14\n\x0csession_data\x18\x02 \x01(\t\"c\n\x15RemoteBrowserResponse\x12&\n\x07session\x18\x01 \x01(\x0b\x32\x15.RemoteBrowserSession\x12\"\n\x05state\x18\x02 \x01(\x0e\x32\x13.RemoteBrowserState*-\n\x12\x42rowserCommandType\x12\x08\n\x04GOTO\x10\x00\x12\r\n\tTERMINATE\x10\x01*>\n\x12RemoteBrowserState\x12\x0b\n\x07RUNNING\x10\x00\x12\x0e\n\nTERMINATED\x10\x01\x12\x0b\n\x07TIMEOUT\x10\x02\x32Q\n\x06Runner\x12G\n\x10GetRemoteBrowser\x12\x15.RemoteBrowserRequest\x1a\x16.RemoteBrowserResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'runner_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BROWSERCOMMANDTYPE._serialized_start=462
  _BROWSERCOMMANDTYPE._serialized_end=507
  _REMOTEBROWSERSTATE._serialized_start=509
  _REMOTEBROWSERSTATE._serialized_end=571
  _BROWSERINPUT._serialized_start=16
  _BROWSERINPUT._serialized_end=79
  _BROWSERINITDATA._serialized_start=81
  _BROWSERINITDATA._serialized_end=206
  _REMOTEBROWSERREQUEST._serialized_start=208
  _REMOTEBROWSERREQUEST._serialized_end=297
  _REMOTEBROWSERSESSION._serialized_start=299
  _REMOTEBROWSERSESSION._serialized_end=359
  _REMOTEBROWSERRESPONSE._serialized_start=361
  _REMOTEBROWSERRESPONSE._serialized_end=460
  _RUNNER._serialized_start=573
  _RUNNER._serialized_end=654
# @@protoc_insertion_point(module_scope)
