# Generated by Django 4.2.1 on 2023-08-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='template_slug',
            field=models.CharField(blank=True, default=None, help_text='Slug of the template used for this app', max_length=100, null=True),
        ),
    ]
