# Generated by Django 4.2.1 on 2023-09-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_app_template_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_uuid', models.UUIDField(blank=True, default=None, help_text='UUID of the app', null=True)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Data for this endpoint')),
                ('comment', models.TextField(blank=True, default='', help_text='Comment for this app version')),
                ('is_draft', models.BooleanField(default=True, help_text='Whether the data is draft or not')),
                ('is_dirty', models.BooleanField(default=False, help_text='Whether the data is dirty or not')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time at which the app instance was created')),
                ('last_updated_at', models.DateTimeField(auto_now=True, help_text='Time at which the app instance was last updated')),
            ],
        ),
    ]
