# Generated by Django 4.2.1 on 2023-09-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_app_data_from_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdata',
            name='version',
            field=models.IntegerField(default=0, help_text='Version of the app'),
        ),
    ]
