# Generated by Django 4.2.1 on 2023-09-28 17:55

import django.contrib.postgres.fields
from django.db import connection, migrations, models

from llmstack.common.utils.db_models import ArrayField


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organizationsettings_anthropic_api_key_and_more'), ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='domains',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    max_length=100),
                default=list,
                help_text='List of allowed domains of the organization',
                size=None) if connection.vendor == 'postgresql' else ArrayField(
                null=True,
                help_text='List of allowed domains of the organization',
                blank=True,
            ),
        ),
    ]
