# Generated by Django 5.0.6 on 2024-06-04 14:33

import django.contrib.postgres.fields
from django.db import connection, migrations, models

from llmstack.common.utils.db_models import ArrayField


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_alter_organization_domains"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="domains",
            field=(
                django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(max_length=100),
                    default=list,
                    help_text="List of allowed domains of the organization",
                    size=None,
                )
                if connection.vendor == "postgresql"
                else ArrayField(
                    null=True,
                    help_text="List of allowed domains of the organization",
                    blank=True,
                )
            ),
        ),
    ]
