# Generated by Django 5.0.6 on 2024-06-04 14:33

import llmstack.common.utils.db_models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_organization_domains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='domains',
            field=llmstack.common.utils.db_models.ArrayField(help_text='List of allowed domains of the organization', null=True),
        ),
    ]
