# Generated by Django 4.2.11 on 2024-07-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_auto_20240610_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='_provider_configs',
            field=models.JSONField(blank=True, default=dict, help_text='Encrypted providers config to use with processors', null=True),
        ),
    ]
