# Generated by Django 5.0.6 on 2024-09-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_populate_provider_configs'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='default_app_access_permission',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Read'), (1, 'Write')], default=0, help_text='Default app access permission for the organization'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='default_datasource_access_permission',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Read'), (1, 'Write')], default=0, help_text='Default datasource access permission for the organization'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='default_datasource_visibility',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Private'), (1, 'Organization')], default=1, help_text='Default datasource visibility for the organization'),
        ),
    ]
