name: Docker Images CI

on:
  push:
    branches: ["main"]
    # Publish semver tags as releases.
    tags:
      - "v*"

env:
  REGISTRY: ghcr.io
  ORG: trypromptly
  IMAGE_NAME_API: "llmstack-api"
  IMAGE_NAME_NGINX: "llmstack-nginx"
  IMAGE_NAME_PLAYWRIGHT: "llmstack-playwright"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.1.1
        with:
          cosign-release: "v2.1.1"

      # Setup QEMU for cross compilation
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata for API
        id: meta-api
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.ORG }}/${{ env.IMAGE_NAME_API }}

      - name: Extract Docker metadata for nginx
        id: meta-nginx
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.ORG }}/${{ env.IMAGE_NAME_NGINX }}

      - name: Extract Docker metadata for playwright
        id: meta-playwright
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.ORG }}/${{ env.IMAGE_NAME_PLAYWRIGHT }}

      # Build client
      - name: Build client
        run: |
          cd client
          npm install
          npm run build

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push LLMStack API Docker image
        id: build-and-push-api
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-api.outputs.tags }}
          labels: ${{ steps.meta-api.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile
          platforms: linux/amd64,linux/arm64

      - name: Build and push LLMStack nginx Docker image
        id: build-and-push-nginx
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-nginx.outputs.tags }}
          labels: ${{ steps.meta-nginx.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile.nginx
          platforms: linux/amd64,linux/arm64
          build-args: |
            REGISTRY=${{ env.REGISTRY }}/${{ env.ORG }}/
            TAG=main

      - name: Build and push LLMStack playwright Docker image
        id: build-and-push-playwright
        uses: docker/build-push-action@v4
        with:
          context: playwright
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-playwright.outputs.tags }}
          labels: ${{ steps.meta-playwright.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: playwright/Dockerfile
          platforms: linux/amd64,linux/arm64

      - name: Sign the published LLMStack API Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
          TAGS: ${{ steps.meta-api.outputs.tags }}
          DIGEST: ${{ steps.build-and-push-api.outputs.digest }}
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

      - name: Sign the published LLMStack nginx Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ steps.meta-nginx.outputs.tags }}
          DIGEST: ${{ steps.build-and-push-nginx.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

      - name: Sign the published LLMStack playwright Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ steps.meta-playwright.outputs.tags }}
          DIGEST: ${{ steps.build-and-push-playwright.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
